const app = require('express')()
const PORT = 6969
const cors = require('cors')

app.use(cors({
    origin: "*"
}))

app.get('/', (req, res) => {
    res.json(
        {
            irregularVerbs: [
                [
                    "arise",
                    "arose",
                    "arouse",
                    "arised",
                    "arisen"
                ],
                ["awake", "awoke", "awoken", "awaked", "awaken"],
                ["be", "was/were", "been", "bed", "wos/wer"],
                ["bear", "bore", "bear", "beared", "boren"],
                ["beat", "beat", "bat", "beated", "boat"],
                ["become", "became", "become", "becamed", "becomed"],
                ["begin", "began", "beginned", "begun", "begin"],
                ["bend", "bent", "bented", "bended", "bond"],
                ["bet", "bet", "bid", "bett", "bot"],
                ["bind", "bound", "binted", "bint", "bund"],
                ["bite", "bit", "bite", "bout", "bote"],
                ["bleed", "bled", "blood", "bleed", "blet"],
                ["blow", "blew", "blown", "blow", "bluw"],
                ["break", "broke", "broken", "break", "breaked"],
                ["breed", "bred", "breed", "brod", "breeded"],
                ["bring", "brought", "brang", "brung", "bring"],
                ["broadcast", "broadcast", "broadcasted", "breadcast", "broadcost"],
                ["build", "built", "build", "builden", "builted"],
                ["burn", "burnt/burned", "burn/burnted", "burnt", "burn"],
                ["burst", "burst", "busted", "bursted", "borst"],
                ["buy", "bought", "boght", "bord", "bored"],
                ["can", "could", "cold", "can", "cauld"],
                ["catch", "caught", "cought", "catched", "cotch"],
                ["choose", "chose", "choose", "chosen", "chuse"],
                ["cling", "clung", "clought", "clang", "cling"],
                ["come", "came", "come", "comm", "comed"],
                ["cost", "cost", "costed", "coast", "coust"],
                ["creep", "crept", "crep", "creeped", "creept"],
                ["cut", "cut", "cutted", "cot", "cutting"],
                ["deal", "dealt", "dealing", "dealed", "deal"],
                ["dig", "dug", "dig", "duck", "digged"],
                ["do", "did", "done", "does", "dod"],
                ["draw", "drew", "drawn", "drewn", "drawed"],
                ["dream", "dreamt/dreamed", "dreamted/dream", "dream", "dreaming"],
                ["drink", "drank", "drunk", "dranken", "dronk"],
                ["drive", "drove", "driven", "drived", "drouve"],
                ["eat", "ate", "eaten", "eating", "eaded"],
                ["fall", "fell", "full", "filled", "falled"],
                ["feed", "fed", "feed", "feet", "fet"],
                ["feel", "felt", "fault", "feeled", "fealt"],
                ["fight", "fought", "foght", "fighted", "fight"],
                ["find", "found", "founded", "fund", "fand"],
                ["fly", "flew", "flown", "flied", "flyed"],
                ["forbid", "forbade", "forbid", "forbad", "forbidden"],
                ["forget", "forgot", "forgotted", "forgetted", "forgit"],
                ["forgive", "forgave", "forgiven", "forgaven", "forgive"],
                ["freeze", "froze", "frooze", "freezed", "frozen"],
                ["get", "got", "gott", "gotten", "getten"],
                ["give", "gave", "given", "gaved", "gouve"],
                ["go", "went", "gone", "got", "goed"],
                ["grind", "ground", "grinded", "grint", "grounded"],
                ["grow", "grew", "grewn", "grown", "gruw"],
                ["hang", "hung", "hang", "hanging", "heng"],
                ["have", "had", "haven", "haved", "have"],
                ["hear", "heard", "heart", "heared", "hearet"],
                ["hide", "hid", "hidden", "hide", "hode"],
                ["hit", "hit", "hitt", "hitted", "hited"],
                ["hold", "held", "hold", "helt", "holded"],
                ["hurt", "hurt", "hurting", "hourt", "hort"],
                ["keep", "kept", "keep", "keeped", "keept"],
                ["kneel", "knelt", "kneelt", "kneeled", "kneed"],
                ["know", "knew", "known", "knewn", "knuw"],
                ["lay", "laid", "layd", "lay", "lait"],
                ["lead", "led", "leat", "lead", "let"],
                ["lean", "leant/leaned", "leanted/lean", "leant", "lean"],
                ["learn", "learnt/learned", "learnted/learn", "learnt", "learn"],
                ["leave", "left", "leaved", "leavt", "leave"],
                ["lend", "lent", "lend", "lended", "lented"],
                ["lie (in bed)", "lay", "laid", "lied", "lain"],
                ["light", "lit/lighted", "light/litted", "litt", "light"],
                ["lose", "lost", "losen", "losed", "losd"],
                ["make", "made", "maked", "maden", "make"],
                ["may", "might", "may", "mayd", "mighted"],
                ["mean", "meant", "meand", "meaned", "meanted"],
                ["meet", "met", "meet", "meeted", "mett"],
                ["pay", "paid", "payed", "paied", "payd"],
                ["put", "put", "putt", "pud", "puted"],
                ["read", "read", "rode", "ride", "ridden"],
                ["ride", "rode", "ridden", "read", "rided"],
                ["ring", "rang", "rung", "ringed", "ranged"],
                ["rise", "rose", "risen", "ruse", "rosed"],
                ["run", "ran", "run", "rann", "runned"],
                ["say", "said", "sayd", "say", "saied"],
                ["see", "saw", "seed", "sawed", "see"],
                ["sell", "sold", "selled", "solled", "seld"],
                ["send", "sent", "send", "sendt", "sended"],
                ["set", "set", "sett", "sedt", "sad"],
                ["shake", "shook", "shaken", "shaked", "shocked"],
                ["shall", "should", "shall", "shalled", "shoud"],
                ["shed", "shed", "shet", "sheded", "shedt"],
                ["shine", "shone", "shine", "shined", "shune"],
                ["shoot", "shot", "shoot", "shout", "shouted"],
                ["shrink", "shrank", "shrunk", "schrank", "shrenk"],
                ["shut", "shut", "shot", "shoot", "shutt"],
                ["sing", "sang", "sung", "song", "sing"],
                ["sink", "sank", "sunk", "sinked", "sanked"],
                ["sit", "sat", "sad", "sid", "sit"],
                ["sleep", "slept", "sleept", "sleeped", "sleeted"],
                ["slide", "slid", "slided", "slide", "slode"],
                ["smell", "smelt", "smell", "smoll", "smeld"],
                ["speak", "spoke", "spoken", "speakt", "speaked"],
                ["spend", "spent", "spend", "spendt", "spenden"],
                ["spit", "spat", "spot", "spitt", "spit"],
                ["spread", "spread", "spreaded", "spred", "spreded"],
                ["stand", "stood", "stand", "standed", "stooden"],
                ["steal", "stole", "stolen", "stealt", "steald"],
                ["stick", "stuck", "stock", "stack", "stick"],
                ["stink", "stank", "stunk", "stink", "stonk"],
                ["strike", "struck", "striked/struck", "stricked/struk", "strike"],
                ["swear", "swore", "sweat", "sweart", "sword"],
                ["sweep", "swept", "sweeped", "swep", "sweep"],
                ["swim", "swam", "swum", "swim", "swom"],
                ["swing", "swung", "swang", "swing", "swong"],
                ["take", "took", "taked", "toked", "taken"],
                ["teach", "taught", "tought", "teaght", "teacht"],
                ["tear", "tore", "tear", "teart", "tored"],
                ["tell", "told", "tellt", "telled", "tolt"],
                ["think", "thought", "thaught", "thank", "thauked"],
                ["throw", "threw", "thrown", "three", "throwed"],
                ["understand", "understood", "understooden", "understanded", "understand"],
                ["wake", "woke", "waken", "woken", "wake"],
                ["wear", "wore", "worn", "wer", "war"],
                ["weep", "wept", "weept", "weepet", "weeped"],
                ["will", "would", "wood", "willt", "willed"],
                ["win", "won", "wan", "woun", "winn"],
                ["wind", "wound", "weind", "wount", "weint"],
                ["write", "wrote", "written", "writted", "write"]

            ],
            curentVocab: [
                ["albeit", "wenn auch", "nicht", "trotzdem", "auch schon"],
                ["uneasy", "unbehaglich", "komisch", "schwer", "nicht leicht"],
                ["counterpart", "Gegenstück", "Gegenteil", "Gegensatz", "Zählerstück"],
                ["(at) random", "zufällig", "Zahl", "Rand", "am randalieren"],
                ["public opinion", "öffentliche Meinung", "Versammlung", "Leichenschau", "Ansehen"],
                ["laudable", "lobenswert", "Lautstärke", "bewusst", "geheim"],
                ["maze", "Irrgarten", "Mücke", "Bank", "Schlüsselloch"],
                ["blame", "Schuld", "blamiert", "Schein", "Brennen"],
                ["agency", "Handlungsfähigkeit", "Kanzlei", "Agent", "Versicherung"],
                ["ausstatten", "(to) endow", "(to) enclove", "(to) enfix", "(to) cover"],
                ["dringend", "urgent", "urgart", "under pressure", "united"],
            ]
        }
    )
})

app.listen(PORT, () => console.log(`Server running on port ${PORT}`))